/*
 * @Description: Sequence contains of actions. Actions could be generated by factories or defined by ourselves.
 * @Author: Li Qingguo
 * @Date: 2019-11-16 19:53:33
 * @FilePath: \main\sequences.js
 * @Environment: Google Chrome 78.0.3904.87 Node 10.15.3
 * @LastEditor: Li Qingguo
 * @LastEditedTime: 2019-11-17 00:51:22
 */

import { props, state } from 'cerebral'
import { set } from 'cerebral/factories'
import * as actions from './actions'

export default {
    loadAllTodos: [
        actions.getTodos,
        set(state`todos`, props`todos`)
    ]
}